{% set name = "cuda-sanitizer-api" %}
{% set version = "13.1.118" %}
{% set cuda_version = "13.1" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set exists = "which" %}  # [not win]
{% set exists = "where" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_sanitizer_api/{{ platform }}/cuda_sanitizer_api-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: b9637777a31cd0f0ffe1e965523e8b0d382019b8496855fd688c886988583cf4  # [linux64]
  sha256: 1dc68ccb146032bcdc9d932569c865d68e3966ecf136940ca38fd7d5abfda4ac  # [aarch64]
  sha256: 9eeb3b8cf7a62d9af40278c52feecc32c57c90e93a163a05112476b436e3575f  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  missing_dso_whitelist:
    - '$RPATH/libInterceptorInjectionTarget.so'  # [linux]
    - '$RPATH/InterceptorInjectionTarget.dll'    # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - patchelf <0.18.0                      # [linux]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf       # [linux]
  files:
    - test-rpath.sh  # [linux]
  commands:
    - test -f $PREFIX/bin/compute-sanitizer                                         # [linux]
    - test -f $PREFIX/compute-sanitizer/compute-sanitizer                           # [linux]
    - if not exist %LIBRARY_PREFIX%\compute-sanitizer\compute-sanitizer.exe exit 1  # [win]
    - if not exist %PREFIX%\Scripts\compute-sanitizer.bat exit 1                    # [win]
    - bash test-rpath.sh                                                            # [linux]
    - {{ exists }} compute-sanitizer
    - compute-sanitizer --version                                                   # [build_platform == target_platform]

about:
  home: https://docs.nvidia.com/compute-sanitizer/SanitizerApiGuide/index.html
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Provides a set of APIs to enable third party tools to write GPU sanitizing tools
  description: |
    Provides a set of APIs to enable third-party tools to write GPU sanitizing
    tools, such as memory and race checkers.
  doc_url: https://docs.nvidia.com/compute-sanitizer/SanitizerApiGuide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
